### ISSUE TITLE
File permissions on docker conversion

### ISSUE THREAD

**Issue by tobiaschielens** [threefoldtech/zero_flist_python#32]
Inside dockerfile jimbersoftware/filebrowser_grid:0.3 the /filebrowser_frontend/dist/index.html has read permission for 'others' while inside the converted flist that is not the case.
Converted flist:
https://hub.grid.tf/tobias.3bot/jimbersoftware-filebrowser_grid-0.3.flist
Docker locally:
![image](https://user-images.githubusercontent.com/17977313/97869851-68373f00-1d12-11eb-82f3-3f6423f2f9c1.png)
Deployed flist:
node:6m9gFPTYLRiCH7FD8yU5VWwXZdfegKUvXZgrJoS1EJfQ
farm:freefarm
pool:765
![image](https://user-images.githubusercontent.com/17977313/97869869-6bcac600-1d12-11eb-8eb8-b2d587469ac4.png)

**Comment by maxux** [comment]
Raw dump from the flist:
```
  File: /filebrowser_frontend/dist/index.html
  Size: 3843 bytes
Access: (664/-rw-rw-r--)  UID: 0 (root), GID: 0 (root)
Access: 1603882015
Create: 1604313614
Chunks: key: 9e2746cc970fef51a1c2a3a4fcc6ce40, decipher: 862f40440506d632746311b976508d54
```
Permissions are not exactly the same (write for group set) but others have write permissions.
The permission we have on your container are completely wrong. I'm checking.

**Comment by maxux** [comment]
Confirmed fixed via https://github.com/threefoldtech/0-fs/pull/45
Not pushed to testnet yet.

**Comment by maxux** [comment]
Pushed to testnet AFAIK
